Video settings
Barteks2x/CubicChunks pull request #141
Opened 2017-01-13 18:25 UTC by Foghrye4

Why can’t automatically merge?

2017-01-13 18:28 UTC, Barteks2x commented
You somehow managed to have different version of CubicChunks class than the one in this repository.

2017-01-13 18:31 UTC, Foghrye4 commented
Rebased to head.

2017-01-13 18:38 UTC, Niko-sk2x requested changes
Reformat all of the code, and show some screenshot.

2017-01-13 18:38 UTC, Barteks2x commented on src/main/java/cubicchunks/CubicChunks.java
> +            chunkGCInterval(1, Integer.MAX_VALUE, 20 * 10,
lowercase enums? really? Took me a while to figure out how you are calling a method without being in some method already...

2017-01-13 18:38 UTC, Barteks2x commented on src/main/java/cubicchunks/CubicChunks.java
> +            {
Formatting...

2017-01-13 18:38 UTC, Barteks2x commented on src/main/java/cubicchunks/client/ClientEventHandler.java
> +        GuiCustomSlider slider = new GuiCustomSlider(buttonId, width / 2 - 155 + 160, 0, option);
More formatting...

2017-01-13 18:38 UTC, Barteks2x commented on src/main/resources/assets/cubicchunks/lang/en_US.lang
> +cubicchunks.gui.cubes=cubes
These 2 can be combined into `Vertical Distance: %d cubes` and you would just use `I18n.format("cubicchunks.gui." + option.name(), option.getValue())`

2017-01-13 18:38 UTC, Foghrye4 commented
Aaargh!

2017-01-13 18:44 UTC, Barteks2x commented
I should rewrite these tests, they only cause issues...

2017-01-14 08:49 UTC, Foghrye4 commented
@Barteks2x test failed because I misplace upper and lower bounds, shame on me. May I skip making screenshots? Trust me, it's working. If you load a world and change value to bigger in singleplayer game, cubes will be loaded.

2017-01-14 15:18 UTC, Barteks2x commented
I meant screenshot of the config screen, becase that's what ou actually added.

2017-01-14 15:38 UTC, Foghrye4 commented
Duh.
![Imgur](http://i.imgur.com/9RKYuYt.png)

2017-01-14 15:52 UTC, Niko-sk2x approved these changes

2017-01-14 15:59 UTC, Barteks2x commented on src/main/java/cubicchunks/CubicChunks.java
> +                char char_ = "_".charAt(0);
I'm almost sure there is some library that already does what this method does.

If you want to go this way, why not use the char literal? `'_' == "_".charAt(0)`

2017-01-14 16:25 UTC, Foghrye4 commented on src/main/java/cubicchunks/CubicChunks.java
> +                char char_ = "_".charAt(0);
There is such thing? Nice.

2017-01-14 16:59 UTC, merged