Tick blocks in cubes
Barteks2x/CubicChunks pull request #237
Opened 2017-06-24 18:18 UTC by Foghrye4

Seems to fix "cube saving console flood" issue. Also works fine.

2017-06-24 18:20 UTC, Foghrye4 commented on src/main/java/cubicchunks/util/XYZPseudoFractalMap.java
> +package cubicchunks.util;
Dunno why its still here. I thought I stash it in another branch.

2017-06-24 21:23 UTC, Barteks2x commented
We should keep it like in vanilla - only 1000 block ticks per server tick. Otherwise the first server tick after world generation will take a long time. I think the best solution would be to just have all the data dumplicated in cubes, and let World do the ticking. Then you would just need a few injections in WorldServer to keep the values in Cubes and in World in sync.

2017-06-25 04:21 UTC, Foghrye4 commented
> have all the data duplicated in cubes, and let World do the ticking.

I don't understand you. Why we should duplicate data in cubes if we don't want to use it?

2017-06-25 12:48 UTC, Barteks2x commented
Oh, it used to be 1000 I think. Maybe they changed it. We would use the data when saving cubes. Instead of filtering, we would use data directly from cubes.

2017-06-25 13:08 UTC, Foghrye4 commented
I don't see anywhere for 'pendingTickListEntriesHashSet' or 'pendingTickListEntriesTreeSet' is accessed for saving this data. Does that data really saved on hard drive?
Also a real goal of this PR is to prevent block updates inside cubes which are not fully populated.

2017-06-25 16:56 UTC, Barteks2x commented
Running block ticks in not-fully-populated areas is ok, because the only situations where these ticks occur is when player places blocks, and in already populated areas. One major case is falling gravel. It doesn't really matter that much when these blocks fall while the cube they are in isn't completely populated, because the place they are in already is populated.

As for where they are accessed - CubicChunks accesses them via reflection, vanilla has a special method that filters them for StructureBoundingBox, but it only uses X and Z coordinates.

And the limit you added also isn't per-world limit. It also may do the updates in the wrong order.

2017-06-25 17:17 UTC, Foghrye4 commented
@Barteks2x so I should add a saving mechanism of 'pendingTickListEntriesTreeSet' on cube saving event and this PR will be OK?

2017-06-25 22:41 UTC, Cyclonit commented on src/main/java/cubicchunks/server/CubeProviderServer.java
>          // NO-OP, This is called by WorldServer's tick() method every tick
This does no longer look like a no-op to me.

2017-07-10 17:01 UTC, Niko-sk2x requested changes

2017-07-10 17:01 UTC, Barteks2x commented on src/main/java/cubicchunks/server/CubeProviderServer.java
>          // NO-OP, This is called by WorldServer's tick() method every tick
You should probably change that. Then it should be ok to merge for now. If I want any further changes, I can do it myself some time later.

2017-07-11 16:19 UTC, Foghrye4 commented
Requested done.

2017-07-11 18:37 UTC, Niko-sk2x approved these changes

2017-07-11 18:37 UTC, merged