CubeWorldEntitySpawner optimisation
Barteks2x/CubicChunks pull request #244
Opened 2017-07-09 17:23 UTC by Foghrye4

2017-07-09 18:09 UTC, Niko-sk2x requested changes
Aside of removing 2 poentially important inner loops, I don't see any major optimizations here. Are you sure the improvement you got isn't just the result of that?

This codebeing slow was also the reason I wanted to implement virtual 32x32x32 cubes.

2017-07-09 18:09 UTC, Niko-sk2x commented on src/main/java/cubicchunks/world/CubeWorldEntitySpawner.java
> +        if(pAmount==0)
Could you reformat the code with the given formatter? Also I belive there is no real performnce benefits in this checks. If there are no players online, the server is idle anyway, no load at all that players could notice.

2017-07-09 18:09 UTC, Niko-sk2x commented on src/main/java/cubicchunks/world/CubeWorldEntitySpawner.java
> +        if (!cubePosList.isEmpty()) {
This could be done as early return. Any reason why it's not done that way? Also this check isn't going to improve performance in any measurable way.

2017-07-09 18:09 UTC, Niko-sk2x commented on src/main/java/cubicchunks/world/CubeWorldEntitySpawner.java
> +            a:for (EnumCreatureType mobType : EnumCreatureType.values()) {
Could you give more descriptive names to labels?

2017-07-09 18:09 UTC, Niko-sk2x commented on src/main/java/cubicchunks/world/CubeWorldEntitySpawner.java
> +                if (shouldSpawnType(mobType, hostileEnable, peacefulEnable, spawnOnSetTickRate)) {
Any reason to change from 
```java
            if (!shouldSpawnType(mobType, hostileEnable, peacefulEnable, spawnOnSetTickRate)) {
                continue;
            }
```
?

2017-07-09 18:09 UTC, Niko-sk2x commented on src/main/java/cubicchunks/world/CubeWorldEntitySpawner.java
> +                    Class<? extends IAnimals> mobTypeClass = mobType.getCreatureClass();
Could you explain (and dd comment) why did you replace `world.countEntities` with this?

2017-07-09 18:09 UTC, Niko-sk2x commented on src/main/java/cubicchunks/world/CubeWorldEntitySpawner.java
> +            currentPlayer = 0;
This will actually slow down mob spawning unless there is something done to prevent that. And it shouldn't cause any changes on one-player server.

2017-07-09 18:09 UTC, Niko-sk2x commented on src/main/java/cubicchunks/world/CubeWorldEntitySpawner.java
> +        if (!player.isSpectator()) {
Again, this could be an early return, this would clearly indicate that nothing happens if the player is spectator, without first looking for the end of that if().

2017-07-09 18:09 UTC, Niko-sk2x commented on src/main/java/cubicchunks/world/CubeWorldEntitySpawner.java
> +            for (int cubeZRel = -SPAWN_RADIUS; cubeZRel <= SPAWN_RADIUS; cubeZRel++)
Formatting again.

2017-07-09 18:09 UTC, Niko-sk2x commented on src/main/java/cubicchunks/world/CubeWorldEntitySpawner.java
> +            if (cubeXRel * cubeXRel + cubeYRel * cubeYRel + cubeZRel * cubeZRel > 8) {
This could get a comment explaining what it does, because it can be very easily confused with distance check to make spwning work only in 8 chunks distance.

2017-07-09 18:09 UTC, Niko-sk2x commented on src/main/java/cubicchunks/world/CubeWorldEntitySpawner.java
> +    private int spawnCreatureTypeInAllChunks(EnumCreatureType mobType, List<CubePos> cubePosList, ICubicWorldServer world) {
Any reason to change argument order?

2017-07-09 18:09 UTC, Barteks2x commented on src/main/java/cubicchunks/world/CubeWorldEntitySpawner.java
> +        for (CubePos cubePos : cubePosList) {
Why rename all these variables?

2017-07-09 18:09 UTC, Barteks2x commented on src/main/java/cubicchunks/world/CubeWorldEntitySpawner.java
> -            int currentPackSize = 0;
I'm not even trying to figure out what you did here, but it seems like you removed a few potentially important loops. Including the part where MC attemots to spawn mobs in groups.

2017-07-09 18:26 UTC, Foghrye4 commented on src/main/java/cubicchunks/world/CubeWorldEntitySpawner.java
> -            int currentPackSize = 0;
@Barteks2x yes. You want those loops back?

2017-07-09 18:34 UTC, Barteks2x commented on src/main/java/cubicchunks/world/CubeWorldEntitySpawner.java
> -            int currentPackSize = 0;
It seems like they are important part of the algorithm, but readding them will probably negate all the performance improvements you got with this.

2017-07-10 18:10 UTC, Foghrye4 commented
I think I found good solution to spawn entities in packs and still more or less fast. Check updated code.

2017-07-13 15:38 UTC, Barteks2x commented
I really doubt that it's actually a good candidate for merging, unless you can prove without reasonable doubt that it actually has the same functionality as vanilla mob spawning.

2017-07-13 15:49 UTC, Foghrye4 commented
@Barteks2x I does not have a same functionality. 
There is a differences: 
1. This spawner does not care if player is spectator or not. It also does not care if cube in range of "spawn radius", it only care if there is no players in range of 24 from possible spawn point.
2. This spawner have additional chance to spawn entity even if chosen spawn point above top solid block of column. To do so it try to spawn entity at a same X and Z as chosen before but at top block + 1 height, additionally checking if cube is send to players.
3. This spawner spawn only one pack of entities (if any) for each type for one server tick. Vanilla spawner spawn up to 3 packs in a same chunk (if possible).
4. This spawner limit amount of added entities by amount of players and type specific limits. Vanilla and old cubic use number of available cubes/chunks (watched and send to players).

There is no other differences.

2017-07-13 15:54 UTC, Barteks2x commented
could you make all these changes optional, with configuration option and limit the amount of changes done to the code so that it's not so hard to compare?

2017-07-13 16:10 UTC, Foghrye4 commented
A best solution in that case is to create two separated versions of `findChunksForSpawning(...)` or even two classes of  CubeWorldEntitySpawner.
I can add a config option for 2 and 3 but 1 and 4 is fundamental difference caused by absolutely different approach on detecting cubes available for spawning.
What would you like to choose?

2017-07-13 16:18 UTC, Barteks2x commented
Removing the limit of spawn radius means that there may be much more ovrall entities spawned, doesn't it cause issues?

Further, setting limit of entities by amount of players means that many players in small area will spawn way more entities than what anyone would consider reasonable, You could boost mob spawning rate by several times just by getting a few people to be close to each other.

So it's basically optimization that really is good only for singleplayer, where the current algorithm is fast enough.

2017-07-13 16:22 UTC, Foghrye4 commented
>Removing the limit of spawn radius means that there may be much more ovrall entities spawned, doesn't it cause issues?

Only one pack spawned per tick.

>Further, setting limit of entities by amount of players means that many players in small area will spawn way more entities than what anyone would consider reasonable, You could boost mob spawning rate by several times just by getting a few people to be close to each other.

Yes. I could switch to size of 'cubeWatchers' map as number defining spawn limit.

So, leave it?

2017-07-13 16:25 UTC, Barteks2x commented
I don't think it's really going to work when done right.

When you use size of cubeWatchers as guide for max amount of entities, you will get huge number with big render distance, and over time spawn much more entities than vanilla has, increasing overall tick time.

2017-07-13 16:29 UTC, Foghrye4 commented
>with big render distance, and over time spawn much more entities than vanilla has

True that. Then `Math.min(type.getMaxNumberOfCreature() * playerList.size(), cubeWatchers.size/divider)`?

2017-07-13 16:30 UTC, Barteks2x commented
This means that with big render distance you are going to spawn much less mobs per cube overall, making it annoyingly hard to actually find any hostile mobs at night.

2017-07-13 16:31 UTC, Foghrye4 commented
As you wish.

2017-07-13 16:31 UTC, closed without merging

2017-07-13 16:34 UTC, Barteks2x commented
Improvement for this code is needed, but the amount of mobs per cube can't vary as you change render distance, and it also can't spawn too many entities (spawning entities everywhere is not an option).

My idea was to use the virtual 32x32x32 cubes there, it would provide up to 8x speedup.