Get block state from cubes
Barteks2x/CubicChunks pull request #249
Opened 2017-07-13 18:20 UTC by Foghrye4

2017-07-13 19:35 UTC, Niko-sk2x requested changes
Just this one change

2017-07-13 19:35 UTC, Barteks2x commented on src/main/java/cubicchunks/asm/mixin/core/common/MixinWorld.java
> +        if (this.isCubicWorld() && this.isValid(pos)) {
You could still cancel it and return AIR if it's not valid

2017-07-14 15:07 UTC, Foghrye4 commented
Done.

2017-07-14 15:07 UTC, Niko-sk2x approved these changes

2017-07-14 15:07 UTC, merged