Optionally run random tick in cubes
Barteks2x/CubicChunks pull request #269
Opened 2017-08-03 15:03 UTC by Foghrye4

2017-08-03 15:43 UTC, Niko-sk2x requested changes

2017-08-03 15:43 UTC, Barteks2x commented on src/main/java/cubicchunks/world/cube/Cube.java
> +        if (!isFullyPopulated || this.storage == null) {
If storage is null light may still need updates

2017-08-03 15:43 UTC, Barteks2x commented on src/main/java/cubicchunks/asm/mixin/selectable/common/MixinWorldServer_UpdateBlocks.java
> +    public void onUpdateBlocks(CallbackInfo ci) {
Could you instead attempt to redirect the right methods to no-ops here or using ModifyVariable? This overwrite would need updating whenever this method is changed and it's a big method. And it's likely that mods will attempt to modify it.

2017-08-03 15:43 UTC, Barteks2x commented on src/main/java/cubicchunks/asm/mixin/core/common/MixinWorld.java
> +    @Override public int updateLCG() {
Why this method is there? It's only used in World mixins.

2017-08-03 18:23 UTC, Foghrye4 commented on src/main/java/cubicchunks/asm/mixin/core/common/MixinWorld.java
> +    @Override public int updateLCG() {
If I will redirect only random tick, it will not be necessary.

2017-08-03 18:59 UTC, Barteks2x commented on src/main/java/cubicchunks/asm/mixin/core/common/MixinWorld.java
> +    @Override public int updateLCG() {
Isn't there a vanilla method that does the same thing? You could use `@Shadow` is there is. If there isn't, you are adding unnecessary changes to `updateBlocks`

2017-08-03 19:35 UTC, Foghrye4 commented
Done as requested.

2017-08-03 21:21 UTC, Barteks2x commented on src/main/java/cubicchunks/server/CubeProviderServer.java
> +    public Iterator<IColumn> columnsIterator() {
Why?

2017-08-03 21:21 UTC, Barteks2x commented on src/main/java/cubicchunks/server/CubeProviderServer.java
> +        profiler.startSection("providerTick(" + cubeMap.getSize() + ")");
You should have done it right when writing this for the first time

2017-08-03 21:21 UTC, Barteks2x commented on src/main/java/cubicchunks/asm/mixin/selectable/common/MixinWorldServer_UpdateBlocks.java
> +        return this.isCubicWorld() ? 0 : gameRules.getInt(ruleName);
Add comment explaining where to look for the real code that does it

2017-08-04 17:21 UTC, Niko-sk2x reviewed
Other than that 'm fine with the code

2017-08-04 17:21 UTC, Barteks2x commented on src/main/java/cubicchunks/asm/CubicChunksMixinConfig.java
> +            writer.name("description");
Gson should support comments is you enable that feature, could you use that instead and simply store the values in normal way?

something like

```java
/* create comment in whatever way needed */
writer.name(configOption.name());
writer.value(configOption.value);
```

2017-08-04 17:44 UTC, Foghrye4 commented on src/main/java/cubicchunks/asm/CubicChunksMixinConfig.java
> +            writer.name("description");
I did not find any mention on how to add a comments of `\\` or `\**\` type in Json files. Even more, I found an info that such comments are not allowed by Json syntax. Existing specifications of JSON format state that JSON must contain tokens and only tokens.
`writer.name("description");` or any other token ignored by parser is acceptable way of adding comments in JSON files.

2017-08-04 17:57 UTC, Barteks2x commented on src/main/java/cubicchunks/asm/CubicChunksMixinConfig.java
> +            writer.name("description");
Looks like Gson supports comments, but there doesn't seem to be a way to write them using the writer. I knowthat json specification doesn't allow them. Then leave the description the way it is, but name and value shoudl be one thing, it makes no sense to do what you did here.

2017-08-04 18:20 UTC, Foghrye4 commented
Generated JSON:
```
[
 {
  "USE_FAST_COLLISION_CHECK": true,
  "description": "Enabling this option allow using fast collision check. Fast collision check can reduce server lag. You need to restart Minecraft to apply changes."
 },
 {
  "RANDOM_TICK_IN_CUBE": true,
  "description": "If set to true, random tick wil be launched from cube instance instead of chunk. Cube based random tick may slightly reduce server lag. You need to restart Minecraft to apply changes."
 }
]
```

2017-08-04 18:39 UTC, Niko-sk2x requested changes

2017-08-04 18:39 UTC, Barteks2x commented on src/main/java/cubicchunks/server/CubeProviderServer.java
> +                cube.randomTick(this.world, rand);
I don't know how I missed it before, but won't it also run when the config option says it should use vanilla code?

2017-08-04 18:39 UTC, Foghrye4 commented on src/main/java/cubicchunks/server/CubeProviderServer.java
> +                cube.randomTick(this.world, rand);
Yes.

2017-08-04 18:45 UTC, Foghrye4 commented on src/main/java/cubicchunks/server/CubeProviderServer.java
> +                cube.randomTick(this.world, rand);
@Barteks2x You mean it should not? Why not?

2017-08-04 19:05 UTC, Barteks2x commented on src/main/java/cubicchunks/server/CubeProviderServer.java
> +                cube.randomTick(this.world, rand);
Because if both run then cubes will be ticked twice

2017-08-05 04:24 UTC, Foghrye4 commented
It will be tick in different blocks. Because we using different random seeds in cube random tick and world random tick. But whatever. I changed it.

2017-08-05 10:28 UTC, Barteks2x commented
But it would mean that for example crops would grow on average twice as fast. So it had to be  fixed.

2017-08-05 10:51 UTC, Niko-sk2x approved these changes

2017-08-05 10:52 UTC, merged