[WIP]Reuse FastBlockAccess across iterations
Barteks2x/CubicChunks pull request #283
Opened 2017-09-17 13:00 UTC by Foghrye4

2017-09-19 13:38 UTC, Niko-sk2x requested changes
I generally would like to avoid touching lighting code too much without proper unit tests for it, but it's already broken anyway in some places and aside of what I mentioned I don't see more bad parts.

2017-09-19 13:38 UTC, Barteks2x commented on src/main/java/cubicchunks/lighting/LightingManager.java
> +        CubePos maxLoad = cube.getCoords().add(1, 1, 1);
This is NOT equivalent to the code I had. Light updates need blocks in radius 17 blocks to be loaded (and there is currently a big in LightPropagator that makes the value even higher in some bad cases when reducing light value)

2017-09-19 13:38 UTC, Barteks2x commented on src/main/java/cubicchunks/lighting/LightingManager.java
> +        ILightBlockAccess blocks = new FastCubeBlockAccess(world.getCubeCache(), cube, 1);
It accidentally works, 1 cube radius isn't enough because of reasons explained in previous comment.

2017-09-19 13:38 UTC, Barteks2x commented on src/main/java/cubicchunks/lighting/LightingManager.java
> +		private ICubicWorld world;
formatting

2017-09-19 13:38 UTC, Barteks2x commented on src/main/java/cubicchunks/lighting/LightingManager.java
> +            CubePos maxLoad = cube.getCoords().add(1, 1, 1);
Again this is not correct

2017-09-19 13:38 UTC, Barteks2x commented on src/main/java/cubicchunks/lighting/LightingManager.java
> +            ILightBlockAccess blocks = new FastCubeBlockAccess(world.getCubeCache(), cube, 1);
Same here

2017-09-22 12:06 UTC, Foghrye4 commented
There is a huge chance that this will not be useful after you finish new lighting code.

2017-09-22 12:06 UTC, closed without merging

2017-09-22 15:15 UTC, Barteks2x commented
It's very likely to still be useful if I don't implement it myself, but would need to be updated.