Chunk Debug Renderer Fix
Barteks2x/CubicChunks pull request #308
Opened 2017-10-22 20:38 UTC by babbaj

Makes the chunk border renderer(f3+g) render relative to the player's Y value

2017-10-22 21:09 UTC, Niko-sk2x requested changes

2017-10-22 21:09 UTC, Barteks2x commented on src/main/java/cubicchunks/asm/mixin/core/client/MixinDebugRenderChunkBorder.java
> +        EntityPlayer player = FMLClientHandler.instance().getClientPlayerEntity();
This should only be enabled for cubic chunks worlds. Inject at HEAD, and cancel if it's cubic chunks world.

2017-10-22 21:09 UTC, Barteks2x commented on src/main/java/cubicchunks/asm/mixin/core/client/MixinDebugRenderChunkBorder.java
> +        double d2 = player.lastTickPosZ + (player.posZ - player.lastTickPosZ) * (double)partialTicks;
convert them to human names. Also mark the places that you changed

2017-10-22 23:44 UTC, babbaj commented
did both

2017-10-23 05:29 UTC, Barteks2x commented on src/main/java/cubicchunks/asm/mixin/core/client/MixinDebugRenderChunkBorder.java
> +            for (int l1 = 0; l1 <= 16; l1 += 16)
More variable names. And formatting. Use the supplied IDEA or eclipse formatter.

2017-10-23 05:29 UTC, Barteks2x commented on src/main/java/cubicchunks/asm/mixin/core/client/MixinDebugRenderChunkBorder.java
> +            double d8 = (double)k1 - playerY;
And here

2017-10-23 12:06 UTC, babbaj commented
formatting??

2017-10-23 13:47 UTC, Barteks2x commented
Curly braces on the same line, not next line (and probably a few other things will be changed if you use [the supplied formatter](https://github.com/OpenCubicChunks/CubicChunks/tree/MC_1.12/code-formatters/intellij-idea-formatter))

2017-10-23 17:42 UTC, babbaj commented
ran intellij's formatter on it

2017-10-23 17:43 UTC, Barteks2x commented
The variable names aren't changed yet, but now it doesn't hurt readability in significant way so I will merge anyway.

2017-10-23 17:43 UTC, Niko-sk2x approved these changes

2017-10-24 08:23 UTC, merged