Vertical View Distance [1.15]
Barteks2x/CubicChunks pull request #538
Opened 2020-06-21 03:23 UTC by AidanLovelace

This PR should be merged *after* [https://github.com/OpenCubicChunks/CubicChunks/pull/537](https://github.com/OpenCubicChunks/CubicChunks/pull/537).

This new PR was created because I did some git nonos on the other branch so I recreated the changes on this branch.

Issue: #519

2020-06-26 00:55 UTC, NotStirred commented
This is not working correctly, it seems to continuously load cubes around the player. Even at render distance 2h2v the same thing happens

2020-06-29 15:19 UTC, AidanLovelace commented
I think I got it properly working now. There were even more oversights. Guess I needed a week not looking at code lol.

2020-06-29 22:28 UTC, NotStirred requested changes
I assume you've rebased to most recent commit, so I haven't addressed those changes.

With a view distance of 8h8v the vertical view is 2 larger than horiz as shown by the vis, so something is not quite right there

2020-06-29 22:28 UTC, NotStirred commented on src/main/java/io/github/opencubicchunks/cubicchunks/CubicChunksConfig.java
> +                .defineInRange("verticalViewDistance", 4, 2, 16);
Match vanilla view distance range
```suggestion
                .defineInRange("verticalViewDistance", 4, 2, 32);
```

2020-06-29 22:28 UTC, NotStirred commented on src/main/java/io/github/opencubicchunks/cubicchunks/chunk/ticket/PlayerCubeTicketTracker.java
> +                    iTicketManager.getCubeTaskPriorityQueueSorter().onUpdateCubeLevel(CubePos.from(pos), () -> this.horizDistances.get(pos), horizCurrentDistance, (horizDistance) -> {
Take vertical view distance into account when sorting cube load tasks
```suggestion
                    iTicketManager.getCubeTaskPriorityQueueSorter().onUpdateCubeLevel(CubePos.from(pos), () -> this.horizDistances.get(pos), horizCurrentDistance+verticalViewDistance, (horizDistance) -> {
```

2020-07-02 04:36 UTC, NotStirred reviewed
Having issues with changing view distance not updating.
Also vertical view of 2 seems to break everything.

2020-07-02 04:36 UTC, NotStirred commented on build.gradle
> +project.ext.lwjglVersion = "3.2.1"
```suggestion
project.ext.lwjglVersion = "3.2.2"
```

2020-07-02 04:36 UTC, NotStirred commented on src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/client/MixinVideoSettingsScreen.java
> +    private static final SliderPercentageOption VERTICAL_RENDER_DISTANCE = new SliderPercentageOption("options.renderDistance", 2.0D, 16.0D, 1.0F, (gameSettings) -> (double) CubicChunksConfig.vertica
```suggestion
    private static final SliderPercentageOption VERTICAL_RENDER_DISTANCE = new SliderPercentageOption("options.renderDistance", 2.0D, 32.0D, 1.0F, (gameSettings) -> (double) CubicChunksConfig.verticalViewDistance.get(),
```

2021-02-16 05:04 UTC, Barteks2x commented
Merged manually, finished and fixed in https://github.com/OpenCubicChunks/CubicChunks/tree/MC_1.17

2021-02-16 05:04 UTC, closed without merging