Fixed teleporting beyond 20,000,000 vertical block limit
Barteks2x/CubicChunks pull request #591
Opened 2020-08-23 01:51 UTC by Setadokalo

Fixes #552, but also exposes the bigger issue of players getting kicked beyond 30,000,000 more, since it is now possible to teleport to positions outside that range. Looking into that next.

2020-08-23 13:02 UTC, NotStirred requested changes
I assume this PR will need a 1.15 equiv?

2020-08-23 13:02 UTC, NotStirred commented on src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinWorld.java
> +        cir.setReturnValue(y < CubicChunks.MIN_SUPPORTED_HEIGHT || y >= CubicChunks.MAX_SUPPORTED_HEIGHT);
I would pick inclusive or exclusive, not a mix of both here

2020-08-23 16:48 UTC, DarkEnchanter1 commented
I didn't test too much, but from what I recall, no - in 1.15 teleportation above 20,000,000 works fine, but it might just not use this method.

2020-08-23 16:50 UTC, DarkEnchanter1 commented on src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinWorld.java
> +        cir.setReturnValue(y < CubicChunks.MIN_SUPPORTED_HEIGHT || y >= CubicChunks.MAX_SUPPORTED_HEIGHT);
I just reused the check that was already in place for the other, similar method in the class - if I make them symmetrical we'd probably need to change the other as well.

2020-08-23 16:53 UTC, NotStirred commented on src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinWorld.java
> +        cir.setReturnValue(y < CubicChunks.MIN_SUPPORTED_HEIGHT || y >= CubicChunks.MAX_SUPPORTED_HEIGHT);
Ah I see, I assume that's due to vanilla doing a similar check, but using exclusive 256 instead of inclusive 255 in `isYOutOfBounds`

2020-08-23 18:54 UTC, DarkEnchanter1 commented
Yeah, after looking into it a bit more, 1.15 doesn't need a similar patch as far as I can see; it doesn't have an equivalent method on `World.class` and teleporting beyond 20,000,000 blocks works fine.

2020-08-24 16:31 UTC, Barteks2x commented
We are not even close to the point where anything beyond +-2048 height range is expected to work. Also it may be better to wait for #570 with this.

2021-02-20 16:14 UTC, AstroOrbis approved these changes

2021-04-30 23:13 UTC, closed without merging