Fix Cubic Nether Generation
Barteks2x/CubicChunks pull request #696
Opened 2021-05-19 00:19 UTC by CorgiTaco

-Adds Nether Aquifers
-Fixes all nether features to work in a cubic context

As it stands it works for the *most* part, still working out the bugs.

2021-05-19 17:41 UTC, CorgiTaco commented
Ready for review :D

2021-05-20 12:11 UTC, alcatrazEscapee reviewed
Corgi asked for performance tips. Obviously, profile it first and foremost but here's some simple first impressions.

2021-05-20 12:11 UTC, alcatrazEscapee commented on src/main/java/io/github/opencubicchunks/cubicchunks/world/gen/feature/LavaLeakFix.java
> +                        }
`Direction.value()` does a full array allocation every time it's invoked. As a result you're allocating (at default config values) up to 32,768 `Direction[]` arrays.

You could reduce that down to one outside the loop, and even strip off the `UP` direction to reduce the need for the `if (...) continue`

2021-05-20 12:11 UTC, alcatrazEscapee commented on src/main/java/io/github/opencubicchunks/cubicchunks/world/gen/feature/LavaLeakFix.java
> +                                SurfaceBuilderConfiguration surfaceBuilderConfiguration = context.level().getBiome(mutable).getGenerationSettings().getSurfaceBuilder().get().config();
Without profiling it's impossible to tell, but I would *very much guess* that the slowest thing in this method is going to be the `getBiome()` call here. As to my understanding it's at the very least making a biome magnifier / zoomer call, which is not the fastest thing in the world. At worst it's re-generating biomes.

2021-06-13 19:24 UTC, CorgiTaco commented
Ready for review stinkies

2021-09-11 02:53 UTC, Barteks2x requested changes

2021-09-11 02:53 UTC, Barteks2x commented on src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinPortalForcer.java
> +        serverChunkCache.addRegionTicket(ticketType, chunkPos, radius, argument); // TODO: Load order?
Column ticket is no longer needed

2021-09-11 02:53 UTC, Barteks2x commented on src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/world/MixinNaturalSpawner.java
> +//        return Coords.cubeToMinBlock(((CubeWorldGenRegion) levelReader).getMainCubeY());
Why is all this commented out code here?

2021-09-13 19:18 UTC, Barteks2x approved these changes

2021-09-13 19:23 UTC, merged